package com.bala.java.jee.jax_rs.application.recipe.controller;

import javax.enterprise.context.RequestScoped;

@RequestScoped
public class RecipeController {

    /**
     * Autogenerated default Constructor stub
     */
    public RecipeController() {
    }
}
